# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGIS2Mapea4
                                 A QGIS plugin
 Genera un visor usando la API de Mapea4
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-18
        copyright            : (C) 2018 by Patricio Soriano :: SIGdeletras
        email                : pasoriano@sigdeletras.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QGIS2Mapea4 class from file QGIS2Mapea4.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis2mapea import QGIS2Mapea4
    return QGIS2Mapea4(iface)
